[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

; Ustawienie prędkości terminala szeregowego na zgodną z naszym kodem
monitor_speed = 115200

; Wskazanie zoptymalizowanej tabeli partycji (plik musi być w tym samym folderze co platformio.ini)
board_build.partitions = custom_ota.csv

; Jeśli masz wersję ESP32-C3 Super Mini, która wymaga sprzętowego USB do wysyłania logów 
; (nic nie widać w konsoli), odkomentuj dwie poniższe linijki:
; build_flags = 
;   -D ARDUINO_USB_MODE=1
;   -D ARDUINO_USB_CDC_ON_BOOT=1

; Automatyczne instalowanie bibliotek - PIO samo pobierze najnowszego NimBLE
lib_deps =
    h2zero/NimBLE-Arduino @ ^2.5.1
